name: Django CI

# Trigger workflow on push or pull requests to main
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      # Optional: add a database service if your Django app uses PostgreSQL/MySQL
      # For SQLite (default), you don't need this

    steps:
      # Step 1: Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"  # match your project version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Step 4: Run migrations
      - name: Run Django migrations
        run: |
          python manage.py migrate

      # Step 5: Run Django tests
      - name: Run Django tests
        run: |
          python manage.py test

      # Step 6: Optional: Lint code (if you have flake8 or pylint)
      - name: Lint code
        run: |
          if command -v flake8 &>/dev/null; then flake8 .; fi
